#include "hierarchy.h"

namespace HIRMutate
{
    namespace DOC
    {
        namespace HIERARCHY
        {
            map<string, vector<string> > offsprings;
            map<string, vector<string> > ancestors;
        }
    }
}

void HIRMutate::DOC::HIERARCHY::initSym()
{
    OFFSPRINGS("AnimationEffectReadOnly", {"KeyframeEffect", "KeyframeEffectReadOnly"})
    OFFSPRINGS("AnimationEffectTimingReadOnly", {"AnimationEffectTiming"})
    OFFSPRINGS("AnimationTimeline", {"DocumentTimeline"})
    OFFSPRINGS("CSSRule", {"CSSKeyframesRule", "CSSStyleRule", "CSSKeyframeRule"})
    OFFSPRINGS("CharacterData", {"CDATASection", "ProcessingInstruction", "Comment", "Text"})
    OFFSPRINGS("DocumentFragment", {"ShadowRoot"})
    OFFSPRINGS("DocumentOrShadowRoot", {"Document", "ShadowRoot"})
    OFFSPRINGS("Element", {"HTMLDataListElement", "HTMLTableRowElement", "SVGGlyphElement", "HTMLBaseFontElement", "HTMLModElement", "SVGFEComponentTransferElement", "SVGMarkerElement", "SVGAnimateColorElement", "SVGDescElement", "HTMLSmallElement", "HTMLCanvasElement", "HTMLMeterElement", "SVGAElement", "HTMLRubyElement", "HTMLFooterElement", "SVGFEMorphologyElement", "HTMLMarqueeElement", "HTMLDListElement", "HTMLSelectElement", "HTMLButtonElement", "SVGGeometryElement", "SVGFEOffsetElement", "HTMLMainElement", "HTMLNavElement", "HTMLHtmlElement", "HTMLUListElement", "SVGFEMergeElement", "SVGHatchpathElement", "HTMLOptGroupElement", "HTMLHRElement", "SVGAnimateMotionElement", "HTMLAsideElement", "HTMLMapElement", "HTMLTrackElement", "HTMLSlotElement", "HTMLPlainTextElement", "SVGSVGElement", "SVGEllipseElement", "HTMLHeaderElement", "HTMLHeading6Element", "HTMLFigureElement", "SVGUseElement", "HTMLProgressElement", "HTMLTextAreaElement", "SVGForeignObjectElement", "HTMLDelElement", "SVGFEDiffuseLightingElement", "SVGFEDistantLightElement", "HTMLTableElement", "HTMLHeading2Element", "SVGRadialGradientElement", "HTMLBigElement", "HTMLIFrameElement", "HTMLRPElement", "HTMLTableColGroupElement", "SVGFontElement", "SVGMPathElement", "HTMLBDOElement", "SVGFEFloodElement", "HTMLPreElement", "HTMLTimeElement", "SVGAnimationElement", "SVGGradientElement", "SVGSwitchElement", "Comment", "HTMLRTElement", "SVGHKernElement", "SVGFEDisplacementMapElement", "SVGImageElement", "SVGSymbolElement", "HTMLAnchorElement", "HTMLDialogElement", "SVGPolylineElement", "HTMLFormElement", "SVGColorProfileElement", "HTMLBaseElement", "HTMLOptionElement", "HTMLParagraphElement", "HTMLContentElement", "SVGMissingGlyphElement", "HTMLMarkElement", "HTMLAudioElement", "HTMLDataElement", "SVGFilterElement", "ShadowRoot", "HTMLFrameElement", "SVGFEConvolveMatrixElement", "SVGGlyphRefElement", "SVGFontFaceUriElement", "SVGAnimateTransformElement", "SVGFEFuncGElement", "SVGFontFaceSrcElement", "HTMLIsIndexElement", "HTMLCenterElement", "HTMLEMElement", "HTMLAcronymElement", "SVGAnimateElement", "SVGPatternElement", "HTMLTemplateElement", "SVGElement", "SVGMetadataElement", "SVGFontFaceNameElement", "SVGLineElement", "HTMLSummaryElement", "HTMLSElement", "HTMLVideoElement", "HTMLDetailsElement", "HTMLSectionElement", "SVGAltGlyphItemElement", "SVGDefsElement", "HTMLDivElement", "HTMLFrameSetElement", "HTMLCiteElement", "HTMLAreaElement", "HTMLScriptElement", "HTMLTBodyElement", "SVGComponentTransferFunctionElement", "HTMLStrikeElement", "HTMLTableDataCellElement", "SVGFEImageElement", "HTMLSupElement", "SVGFEMergeNodeElement", "SVGFETurbulenceElement", "HTMLWBRElement", "SVGRectElement", "HTMLDirectoryElement", "HTMLBgSoundElement", "DocumentFragment", "SVGCircleElement", "SVGFEFuncBElement", "HTMLOListElement", "SVGFontFaceFormatElement", "HTMLParamElement", "HTMLDFNElement", "HTMLImageElement", "HTMLBodyElement", "HTMLUElement", "HTMLHeading1Element", "HTMLBRElement", "HTMLAddressElement", "HTMLDDElement", "SVGViewElement", "HTMLFontElement", "HTMLVarElement", "SVGLinearGradientElement", "HTMLInputElement", "SVGFEPointLightElement", "HTMLMetaElement", "HTMLSampElement", "HTMLKBDElement", "HTMLQuoteElement", "SVGPathElement", "SVGPolygonElement", "Text", "HTMLHGroupElement", "HTMLObjectElement", "HTMLHeading5Element", "SVGSetElement", "HTMLXMPElement", "HTMLDTElement", "SVGHatchElement", "HTMLArticleElement", "SVGTSpanElement", "HTMLQElement", "SVGFEFuncAElement", "HTMLHeading3Element", "HTMLBDIElement", "HTMLLegendElement", "HTMLTTElement", "HTMLInsElement", "SVGTextContentElement", "SVGFEDropShadowElement", "HTMLStrongElement", "SVGAltGlyphElement", "SVGTextPositioningElement", "HTMLHeading4Element", "SVGFEBlendElement", "HTMLLIElement", "HTMLSourceElement", "CharacterData", "SVGFEGaussianBlurElement", "SVGCursorElement", "SVGDiscardElement", "SVGMaskElement", "HTMLPictureElement", "SVGSolidcolorElement", "HTMLSpanElement", "SVGFESpotLightElement", "HTMLSubElement", "HTMLTableSectionElement", "SVGFESpecularLightingElement", "SVGFETileElement", "HTMLShadowElement", "HTMLLabelElement", "SVGTextPathElement", "HTMLCommandElement", "HTMLHeadingElement", "HTMLMenuElement", "SVGAltGlyphDefElement", "SVGClipPathElement", "HTMLTableColElement", "SVGTRefElement", "HTMLTableCaptionElement", "HTMLFigCaptionElement", "HTMLMenuItemElement", "SVGStopElement", "SVGFEColorMatrixElement", "SVGFEFuncRElement", "HTMLStyleElement", "HTMLHeadElement", "CDATASection", "HTMLTableHeaderCellElement", "HTMLTitleElement", "SVGFECompositeElement", "SVGScriptElement", "SVGStyleElement", "SVGTextElement", "HTMLMediaElement", "SVGGElement", "HTMLTHeadElement", "ProcessingInstruction", "SVGVKernElement", "HTMLCodeElement", "SVGGraphicsElement", "HTMLEmbedElement", "HTMLElement", "HTMLAbbrElement", "HTMLBElement", "SVGTitleElement", "SVGFontFaceElement", "HTMLOutputElement", "HTMLIElement", "HTMLFieldSetElement", "HTMLBlockQuoteElement", "HTMLLinkElement", "HTMLTFootElement", "HTMLKeygenElement", "HTMLListingElement"})
    OFFSPRINGS("Event", {"ProgressEvent", "SecurityPolicyViolationEvent", "TransitionEvent", "AnimationPlaybackEvent", "CustomEvent", "KeyboardEvent", "ErrorEvent", "TextEvent", "MouseEvent", "PointerEvent", "PageTransitionEvent", "ApplicationCacheErrorEvent", "HashChangeEvent", "WheelEvent", "MutationEvent", "MessageEvent", "AnimationEvent", "InputEvent", "ClipboardEvent", "PromiseRejectionEvent", "ResourceProgressEvent", "UIEvent", "MediaQueryListEvent", "BeforeUnloadEvent", "DragEvent", "CompositionEvent", "PopStateEvent", "FocusEvent"})
    OFFSPRINGS("EventTarget", {"HTMLDataListElement", "HTMLTableRowElement", "SVGGlyphElement", "HTMLBaseFontElement", "HTMLModElement", "SVGFEComponentTransferElement", "SVGMarkerElement", "SVGAnimateColorElement", "SVGDescElement", "HTMLSmallElement", "HTMLCanvasElement", "HTMLMeterElement", "SVGAElement", "Element", "HTMLRubyElement", "HTMLFooterElement", "SVGFEMorphologyElement", "HTMLMarqueeElement", "HTMLDListElement", "HTMLSelectElement", "HTMLButtonElement", "SVGGeometryElement", "SVGFEOffsetElement", "HTMLMainElement", "HTMLNavElement", "HTMLHtmlElement", "HTMLUListElement", "SVGFEMergeElement", "SVGHatchpathElement", "HTMLOptGroupElement", "HTMLHRElement", "SVGAnimateMotionElement", "HTMLAsideElement", "HTMLMapElement", "HTMLTrackElement", "HTMLSlotElement", "HTMLPlainTextElement", "SVGSVGElement", "SVGEllipseElement", "HTMLHeaderElement", "HTMLHeading6Element", "HTMLFigureElement", "SVGUseElement", "HTMLProgressElement", "HTMLTextAreaElement", "SVGForeignObjectElement", "HTMLDelElement", "SVGFEDiffuseLightingElement", "SVGFEDistantLightElement", "HTMLTableElement", "HTMLHeading2Element", "SVGRadialGradientElement", "HTMLBigElement", "HTMLIFrameElement", "HTMLRPElement", "HTMLTableColGroupElement", "SVGFontElement", "SVGMPathElement", "HTMLBDOElement", "SVGFEFloodElement", "HTMLPreElement", "HTMLTimeElement", "SVGAnimationElement", "SVGGradientElement", "SVGSwitchElement", "Comment", "HTMLRTElement", "SVGHKernElement", "SVGFEDisplacementMapElement", "SVGImageElement", "SVGSymbolElement", "HTMLAnchorElement", "HTMLDialogElement", "SVGPolylineElement", "HTMLFormElement", "SVGColorProfileElement", "HTMLBaseElement", "HTMLOptionElement", "HTMLParagraphElement", "HTMLContentElement", "SVGMissingGlyphElement", "HTMLMarkElement", "HTMLAudioElement", "HTMLDataElement", "SVGFilterElement", "ShadowRoot", "HTMLFrameElement", "SVGFEConvolveMatrixElement", "SVGGlyphRefElement", "SVGFontFaceUriElement", "SVGAnimateTransformElement", "SVGFEFuncGElement", "SVGFontFaceSrcElement", "HTMLIsIndexElement", "HTMLCenterElement", "HTMLEMElement", "HTMLAcronymElement", "SVGAnimateElement", "SVGPatternElement", "HTMLTemplateElement", "SVGElement", "SVGMetadataElement", "SVGFontFaceNameElement", "SVGLineElement", "HTMLSummaryElement", "HTMLSElement", "HTMLVideoElement", "HTMLDetailsElement", "HTMLSectionElement", "SVGAltGlyphItemElement", "SVGDefsElement", "HTMLDivElement", "HTMLFrameSetElement", "HTMLCiteElement", "HTMLAreaElement", "HTMLScriptElement", "HTMLTBodyElement", "SVGComponentTransferFunctionElement", "HTMLStrikeElement", "HTMLTableDataCellElement", "SVGFEImageElement", "HTMLSupElement", "SVGFEMergeNodeElement", "SVGFETurbulenceElement", "HTMLWBRElement", "SVGRectElement", "HTMLDirectoryElement", "HTMLBgSoundElement", "DocumentFragment", "SVGCircleElement", "SVGFEFuncBElement", "HTMLOListElement", "SVGFontFaceFormatElement", "HTMLParamElement", "HTMLDFNElement", "HTMLImageElement", "HTMLBodyElement", "HTMLUElement", "HTMLHeading1Element", "HTMLBRElement", "HTMLAddressElement", "HTMLDDElement", "SVGViewElement", "HTMLFontElement", "HTMLVarElement", "SVGLinearGradientElement", "HTMLInputElement", "SVGFEPointLightElement", "HTMLMetaElement", "HTMLSampElement", "HTMLKBDElement", "HTMLQuoteElement", "SVGPathElement", "SVGPolygonElement", "Text", "HTMLHGroupElement", "HTMLObjectElement", "HTMLHeading5Element", "SVGSetElement", "HTMLXMPElement", "HTMLDTElement", "SVGHatchElement", "HTMLArticleElement", "SVGTSpanElement", "HTMLQElement", "SVGFEFuncAElement", "HTMLHeading3Element", "HTMLBDIElement", "HTMLLegendElement", "HTMLTTElement", "HTMLInsElement", "SVGTextContentElement", "SVGFEDropShadowElement", "HTMLStrongElement", "SVGAltGlyphElement", "SVGTextPositioningElement", "HTMLHeading4Element", "SVGFEBlendElement", "HTMLLIElement", "HTMLSourceElement", "CharacterData", "SVGFEGaussianBlurElement", "SVGCursorElement", "SVGDiscardElement", "SVGMaskElement", "HTMLPictureElement", "SVGSolidcolorElement", "HTMLSpanElement", "SVGFESpotLightElement", "HTMLSubElement", "HTMLTableSectionElement", "SVGFESpecularLightingElement", "SVGFETileElement", "HTMLShadowElement", "HTMLLabelElement", "SVGTextPathElement", "Window", "HTMLCommandElement", "HTMLHeadingElement", "HTMLMenuElement", "SVGAltGlyphDefElement", "SVGClipPathElement", "HTMLTableColElement", "SVGTRefElement", "HTMLTableCaptionElement", "HTMLFigCaptionElement", "HTMLMenuItemElement", "SVGStopElement", "SVGFEColorMatrixElement", "SVGFEFuncRElement", "HTMLStyleElement", "HTMLHeadElement", "CDATASection", "HTMLTableHeaderCellElement", "HTMLTitleElement", "SVGFECompositeElement", "SVGScriptElement", "SVGStyleElement", "SVGTextElement", "HTMLMediaElement", "SVGGElement", "HTMLTHeadElement", "ProcessingInstruction", "Document", "HTMLCodeElement", "SVGGraphicsElement", "SVGVKernElement", "HTMLEmbedElement", "HTMLElement", "HTMLAbbrElement", "HTMLBElement", "SVGTitleElement", "SVGFontFaceElement", "HTMLOutputElement", "HTMLIElement", "HTMLFieldSetElement", "HTMLBlockQuoteElement", "HTMLLinkElement", "HTMLTFootElement", "HTMLKeygenElement", "HTMLListingElement"})
    OFFSPRINGS("HTMLElement", {"HTMLDataListElement", "HTMLTableRowElement", "HTMLBaseFontElement", "HTMLModElement", "HTMLSmallElement", "HTMLCanvasElement", "HTMLMeterElement", "HTMLRubyElement", "HTMLFooterElement", "HTMLMarqueeElement", "HTMLDListElement", "HTMLSelectElement", "HTMLButtonElement", "HTMLMainElement", "HTMLNavElement", "HTMLHtmlElement", "HTMLUListElement", "HTMLOptGroupElement", "HTMLHRElement", "HTMLAsideElement", "HTMLMapElement", "HTMLTrackElement", "HTMLSlotElement", "HTMLPlainTextElement", "HTMLHeaderElement", "HTMLHeading6Element", "HTMLFigureElement", "HTMLProgressElement", "HTMLTextAreaElement", "HTMLDelElement", "HTMLTableElement", "HTMLHeading2Element", "HTMLBigElement", "HTMLIFrameElement", "HTMLRPElement", "HTMLTableColGroupElement", "HTMLBDOElement", "HTMLPreElement", "HTMLTimeElement", "HTMLRTElement", "HTMLAnchorElement", "HTMLDialogElement", "HTMLFormElement", "HTMLBaseElement", "HTMLOptionElement", "HTMLParagraphElement", "HTMLContentElement", "HTMLMarkElement", "HTMLAudioElement", "HTMLDataElement", "HTMLFrameElement", "HTMLIsIndexElement", "HTMLCenterElement", "HTMLEMElement", "HTMLAcronymElement", "HTMLTemplateElement", "HTMLSummaryElement", "HTMLSElement", "HTMLVideoElement", "HTMLDetailsElement", "HTMLSectionElement", "HTMLDivElement", "HTMLFrameSetElement", "HTMLCiteElement", "HTMLAreaElement", "HTMLScriptElement", "HTMLTBodyElement", "HTMLStrikeElement", "HTMLTableDataCellElement", "HTMLSupElement", "HTMLWBRElement", "HTMLDirectoryElement", "HTMLBgSoundElement", "HTMLOListElement", "HTMLParamElement", "HTMLDFNElement", "HTMLImageElement", "HTMLBodyElement", "HTMLUElement", "HTMLHeading1Element", "HTMLBRElement", "HTMLAddressElement", "HTMLDDElement", "HTMLFontElement", "HTMLVarElement", "HTMLInputElement", "HTMLMetaElement", "HTMLSampElement", "HTMLKBDElement", "HTMLQuoteElement", "HTMLHeading5Element", "HTMLHGroupElement", "HTMLObjectElement", "HTMLXMPElement", "HTMLDTElement", "HTMLArticleElement", "HTMLQElement", "HTMLHeading3Element", "HTMLBDIElement", "HTMLLegendElement", "HTMLTTElement", "HTMLInsElement", "HTMLStrongElement", "HTMLHeading4Element", "HTMLLIElement", "HTMLSourceElement", "HTMLPictureElement", "HTMLSpanElement", "HTMLSubElement", "HTMLTableSectionElement", "HTMLShadowElement", "HTMLLabelElement", "HTMLCommandElement", "HTMLHeadingElement", "HTMLMenuElement", "HTMLTableColElement", "HTMLTableCaptionElement", "HTMLFigCaptionElement", "HTMLMenuItemElement", "HTMLStyleElement", "HTMLHeadElement", "HTMLTableHeaderCellElement", "HTMLTitleElement", "HTMLMediaElement", "HTMLTHeadElement", "HTMLCodeElement", "HTMLEmbedElement", "HTMLAbbrElement", "HTMLBElement", "HTMLOutputElement", "HTMLIElement", "HTMLFieldSetElement", "HTMLBlockQuoteElement", "HTMLLinkElement", "HTMLTFootElement", "HTMLKeygenElement", "HTMLListingElement"})
    OFFSPRINGS("HTMLHeadingElement", {"HTMLHeading2Element", "HTMLHeading1Element", "HTMLHeading4Element", "HTMLHeading3Element", "HTMLHeading5Element", "HTMLHeading6Element"})
    OFFSPRINGS("HTMLMediaElement", {"HTMLVideoElement", "HTMLAudioElement"})
    OFFSPRINGS("HTMLModElement", {"HTMLDelElement", "HTMLInsElement"})
    OFFSPRINGS("HTMLQuoteElement", {"HTMLBlockQuoteElement", "HTMLQElement"})
    OFFSPRINGS("HTMLTableCellElement", {"HTMLTableHeaderCellElement", "HTMLTableDataCellElement"})
    OFFSPRINGS("HTMLTableColElement", {"HTMLTableColGroupElement"})
    OFFSPRINGS("HTMLTableSectionElement", {"HTMLTBodyElement", "HTMLTHeadElement", "HTMLTFootElement"})
    OFFSPRINGS("KeyframeEffectReadOnly", {"KeyframeEffect"})
    OFFSPRINGS("MouseEvent", {"WheelEvent", "PointerEvent", "DragEvent"})
    OFFSPRINGS("ProgressEvent", {"ResourceProgressEvent"})
    OFFSPRINGS("SVGAnimationElement", {"SVGAnimateTransformElement", "SVGSetElement", "SVGAnimateElement", "SVGAnimateMotionElement", "SVGAnimateColorElement"})
    OFFSPRINGS("SVGComponentTransferFunctionElement", {"SVGFEFuncGElement", "SVGFEFuncRElement", "SVGFEFuncBElement", "SVGFEFuncAElement"})
    OFFSPRINGS("SVGElement", {"SVGGlyphElement", "SVGFEComponentTransferElement", "SVGMarkerElement", "SVGAnimateColorElement", "SVGDescElement", "SVGAElement", "SVGFEMorphologyElement", "SVGGeometryElement", "SVGFEOffsetElement", "SVGFEMergeElement", "SVGHatchpathElement", "SVGAnimateMotionElement", "SVGSVGElement", "SVGEllipseElement", "SVGUseElement", "SVGForeignObjectElement", "SVGFEDiffuseLightingElement", "SVGFEDistantLightElement", "SVGRadialGradientElement", "SVGFontElement", "SVGMPathElement", "SVGFEFloodElement", "SVGAnimationElement", "SVGGradientElement", "SVGSwitchElement", "SVGHKernElement", "SVGFEDisplacementMapElement", "SVGImageElement", "SVGSymbolElement", "SVGPolylineElement", "SVGColorProfileElement", "SVGMissingGlyphElement", "SVGFilterElement", "SVGFEConvolveMatrixElement", "SVGGlyphRefElement", "SVGFontFaceUriElement", "SVGAnimateTransformElement", "SVGFEFuncGElement", "SVGFontFaceSrcElement", "SVGAnimateElement", "SVGPatternElement", "SVGMetadataElement", "SVGFontFaceNameElement", "SVGLineElement", "SVGAltGlyphItemElement", "SVGDefsElement", "SVGComponentTransferFunctionElement", "SVGGElement", "SVGFEMergeNodeElement", "SVGFEImageElement", "SVGFETurbulenceElement", "SVGRectElement", "SVGCircleElement", "SVGFEFuncBElement", "SVGFontFaceFormatElement", "SVGViewElement", "SVGLinearGradientElement", "SVGFEPointLightElement", "SVGPathElement", "SVGPolygonElement", "SVGSetElement", "SVGHatchElement", "SVGTSpanElement", "SVGFEFuncAElement", "SVGTextContentElement", "SVGFEDropShadowElement", "SVGAltGlyphElement", "SVGTextPositioningElement", "SVGFEBlendElement", "SVGFEGaussianBlurElement", "SVGCursorElement", "SVGDiscardElement", "SVGMaskElement", "SVGSolidcolorElement", "SVGFESpotLightElement", "SVGFESpecularLightingElement", "SVGFETileElement", "SVGTextPathElement", "SVGAltGlyphDefElement", "SVGClipPathElement", "SVGTRefElement", "SVGStopElement", "SVGFEColorMatrixElement", "SVGFEFuncRElement", "SVGFECompositeElement", "SVGScriptElement", "SVGStyleElement", "SVGTextElement", "SVGVKernElement", "SVGGraphicsElement", "SVGTitleElement", "SVGFontFaceElement"})
    OFFSPRINGS("SVGFilterPrimitiveStandardAttributes", {"SVGFEBlendElement", "SVGFEGaussianBlurElement", "SVGFEFloodElement", "SVGFEFuncBElement", "SVGFEComponentTransferElement", "SVGFEDisplacementMapElement", "SVGFESpotLightElement", "SVGFESpecularLightingElement", "SVGFETileElement", "SVGFEMorphologyElement", "SVGFEPointLightElement", "SVGFEOffsetElement", "SVGFEColorMatrixElement", "SVGFEFuncRElement", "SVGFEMergeElement", "SVGFEConvolveMatrixElement", "SVGFEFuncGElement", "SVGFECompositeElement", "SVGFETurbulenceElement", "SVGFEFuncAElement", "SVGFEDropShadowElement", "SVGFEMergeNodeElement", "SVGFEImageElement", "SVGFEDiffuseLightingElement", "SVGFEDistantLightElement"})
    OFFSPRINGS("SVGFitToViewBox", {"SVGViewElement", "SVGPatternElement", "SVGMarkerElement", "SVGViewSpec", "SVGSymbolElement", "SVGSVGElement"})
    OFFSPRINGS("SVGGeometryElement", {"SVGLineElement", "SVGEllipseElement", "SVGCircleElement", "SVGPolylineElement", "SVGPathElement", "SVGRectElement", "SVGPolygonElement"})
    OFFSPRINGS("SVGGradientElement", {"SVGRadialGradientElement", "SVGLinearGradientElement"})
    OFFSPRINGS("SVGGraphicsElement", {"SVGCircleElement", "SVGSwitchElement", "SVGImageElement", "SVGSymbolElement", "SVGAElement", "SVGTextPathElement", "SVGPolylineElement", "SVGTRefElement", "SVGGeometryElement", "SVGPathElement", "SVGPolygonElement", "SVGTextElement", "SVGTSpanElement", "SVGSVGElement", "SVGLineElement", "SVGEllipseElement", "SVGDefsElement", "SVGGElement", "SVGTextContentElement", "SVGUseElement", "SVGForeignObjectElement", "SVGAltGlyphElement", "SVGTextPositioningElement", "SVGRectElement"})
    OFFSPRINGS("SVGPathSeg", {"SVGPathSegCurvetoQuadraticSmoothRel", "SVGPathSegCurvetoQuadraticAbs", "SVGPathSegLinetoVerticalAbs", "SVGPathSegCurvetoQuadraticRel", "SVGPathSegLinetoVerticalRel", "SVGPathSegLinetoHorizontalRel", "SVGPathSegArcAbs", "SVGPathSegCurvetoCubicRel", "SVGPathSegCurvetoCubicSmoothRel", "SVGPathSegArcRel", "SVGPathSegClosePath", "SVGPathSegLinetoRel", "SVGPathSegLinetoAbs", "SVGPathSegCurvetoCubicSmoothAbs", "SVGPathSegMovetoRel", "SVGPathSegLinetoHorizontalAbs", "SVGPathSegCurvetoCubicAbs", "SVGPathSegCurvetoQuadraticSmoothAbs", "SVGPathSegMovetoAbs"})
    OFFSPRINGS("SVGTextContentElement", {"SVGTextPathElement", "SVGTextElement", "SVGTRefElement", "SVGTSpanElement", "SVGTextPositioningElement"})
    OFFSPRINGS("SVGTextPositioningElement", {"SVGTRefElement", "SVGTSpanElement", "SVGTextElement"})
    OFFSPRINGS("SVGURIReference", {"SVGTextPathElement", "SVGRadialGradientElement", "SVGColorProfileElement", "SVGMPathElement", "SVGScriptElement", "SVGCursorElement", "SVGLinearGradientElement", "SVGGradientElement", "SVGPatternElement", "SVGTRefElement", "SVGFilterElement", "SVGUseElement", "SVGFEImageElement", "SVGImageElement", "SVGAElement", "SVGAltGlyphElement", "SVGGlyphRefElement"})
    OFFSPRINGS("SVGZoomAndPan", {"SVGViewSpec", "SVGSVGElement", "SVGViewElement"})
    OFFSPRINGS("ShadowHost", {"HTMLFooterElement", "HTMLHeading1Element", "HTMLHeading2Element", "HTMLHeading3Element", "HTMLHeading4Element", "HTMLHeading5Element", "HTMLSectionElement", "HTMLHeaderElement", "HTMLParagraphElement", "HTMLHeading6Element", "HTMLDivElement", "HTMLArticleElement", "HTMLAsideElement", "HTMLBlockQuoteElement", "HTMLSpanElement", "HTMLMainElement", "HTMLNavElement", "HTMLBodyElement"})
    OFFSPRINGS("StyleSheet", {"CSSStyleSheet", "CSSKeyframesSheet"})
    OFFSPRINGS("Text", {"CDATASection"})
    OFFSPRINGS("TextTrackCue", {"VTTCue"})
    OFFSPRINGS("UIEvent", {"WheelEvent", "KeyboardEvent", "DragEvent", "CompositionEvent", "MouseEvent", "TextEvent", "InputEvent", "PointerEvent", "FocusEvent"})

    ANCESTORS("AnimationEffectTiming", {"AnimationEffectTimingReadOnly"})
    ANCESTORS("AnimationEvent", {"Event"})
    ANCESTORS("AnimationPlaybackEvent", {"Event"})
    ANCESTORS("ApplicationCacheErrorEvent", {"Event"})
    ANCESTORS("BeforeUnloadEvent", {"Event"})
    ANCESTORS("CDATASection", {"CharacterData", "EventTarget", "Text", "Element"})
    ANCESTORS("CSSKeyframeRule", {"CSSRule"})
    ANCESTORS("CSSKeyframesRule", {"CSSRule"})
    ANCESTORS("CSSKeyframesSheet", {"StyleSheet"})
    ANCESTORS("CSSStyleRule", {"CSSRule"})
    ANCESTORS("CSSStyleSheet", {"StyleSheet"})
    ANCESTORS("CharacterData", {"EventTarget", "Element"})
    ANCESTORS("ClipboardEvent", {"Event"})
    ANCESTORS("Comment", {"CharacterData", "EventTarget", "Element"})
    ANCESTORS("CompositionEvent", {"Event", "UIEvent"})
    ANCESTORS("CustomEvent", {"Event"})
    ANCESTORS("Document", {"EventTarget", "DocumentOrShadowRoot"})
    ANCESTORS("DocumentFragment", {"EventTarget", "Element"})
    ANCESTORS("DocumentTimeline", {"AnimationTimeline"})
    ANCESTORS("DragEvent", {"Event", "MouseEvent", "UIEvent"})
    ANCESTORS("Element", {"EventTarget"})
    ANCESTORS("ErrorEvent", {"Event"})
    ANCESTORS("FocusEvent", {"Event", "UIEvent"})
    ANCESTORS("HTMLAbbrElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLAcronymElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLAddressElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLAnchorElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLAreaElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLArticleElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLAsideElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLAudioElement", {"HTMLElement", "HTMLMediaElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBDIElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBDOElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBRElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBaseElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBaseFontElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBgSoundElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBigElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLBlockQuoteElement", {"HTMLElement", "EventTarget", "ShadowHost", "HTMLQuoteElement", "Element"})
    ANCESTORS("HTMLBodyElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLButtonElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLCanvasElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLCenterElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLCiteElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLCodeElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLCommandElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLContentElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDDElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDFNElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDListElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDTElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDataElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDataListElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDelElement", {"HTMLModElement", "Element", "EventTarget", "HTMLElement"})
    ANCESTORS("HTMLDetailsElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDialogElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDirectoryElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLDivElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLEMElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLElement", {"EventTarget", "Element"})
    ANCESTORS("HTMLEmbedElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLFieldSetElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLFigCaptionElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLFigureElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLFontElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLFooterElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLFormElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLFrameElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLFrameSetElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLHGroupElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLHRElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLHeadElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLHeaderElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLHeading1Element", {"HTMLElement", "EventTarget", "HTMLHeadingElement", "ShadowHost", "Element"})
    ANCESTORS("HTMLHeading2Element", {"HTMLElement", "EventTarget", "HTMLHeadingElement", "ShadowHost", "Element"})
    ANCESTORS("HTMLHeading3Element", {"HTMLElement", "EventTarget", "HTMLHeadingElement", "ShadowHost", "Element"})
    ANCESTORS("HTMLHeading4Element", {"HTMLElement", "EventTarget", "HTMLHeadingElement", "ShadowHost", "Element"})
    ANCESTORS("HTMLHeading5Element", {"HTMLElement", "EventTarget", "HTMLHeadingElement", "ShadowHost", "Element"})
    ANCESTORS("HTMLHeading6Element", {"HTMLElement", "EventTarget", "HTMLHeadingElement", "ShadowHost", "Element"})
    ANCESTORS("HTMLHeadingElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLHtmlElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLIElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLIFrameElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLImageElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLInputElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLInsElement", {"HTMLModElement", "Element", "EventTarget", "HTMLElement"})
    ANCESTORS("HTMLIsIndexElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLKBDElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLKeygenElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLLIElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLLabelElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLLegendElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLLinkElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLListingElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMainElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLMapElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMarkElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMarqueeElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMediaElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMenuElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMenuItemElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMetaElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLMeterElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLModElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLNavElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLOListElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLObjectElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLOptGroupElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLOptionElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLOutputElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLParagraphElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLParamElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLPictureElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLPlainTextElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLPreElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLProgressElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLQElement", {"HTMLElement", "EventTarget", "Element", "HTMLQuoteElement"})
    ANCESTORS("HTMLQuoteElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLRPElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLRTElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLRubyElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSampElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLScriptElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSectionElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLSelectElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLShadowElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSlotElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSmallElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSourceElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSpanElement", {"HTMLElement", "EventTarget", "Element", "ShadowHost"})
    ANCESTORS("HTMLStrikeElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLStrongElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLStyleElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSubElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSummaryElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLSupElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTBodyElement", {"HTMLElement", "Element", "EventTarget", "HTMLTableSectionElement"})
    ANCESTORS("HTMLTFootElement", {"HTMLElement", "Element", "EventTarget", "HTMLTableSectionElement"})
    ANCESTORS("HTMLTHeadElement", {"HTMLElement", "Element", "EventTarget", "HTMLTableSectionElement"})
    ANCESTORS("HTMLTTElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTableCaptionElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTableColElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTableColGroupElement", {"HTMLElement", "Element", "EventTarget", "HTMLTableColElement"})
    ANCESTORS("HTMLTableDataCellElement", {"HTMLElement", "HTMLTableCellElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTableElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTableHeaderCellElement", {"HTMLElement", "HTMLTableCellElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTableRowElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTableSectionElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTemplateElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTextAreaElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTimeElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTitleElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLTrackElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLUElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLUListElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLVarElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLVideoElement", {"HTMLElement", "HTMLMediaElement", "EventTarget", "Element"})
    ANCESTORS("HTMLWBRElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HTMLXMPElement", {"HTMLElement", "EventTarget", "Element"})
    ANCESTORS("HashChangeEvent", {"Event"})
    ANCESTORS("InputEvent", {"Event", "UIEvent"})
    ANCESTORS("KeyboardEvent", {"Event", "UIEvent"})
    ANCESTORS("KeyframeEffect", {"AnimationEffectReadOnly", "KeyframeEffectReadOnly"})
    ANCESTORS("KeyframeEffectReadOnly", {"AnimationEffectReadOnly"})
    ANCESTORS("MediaQueryListEvent", {"Event"})
    ANCESTORS("MessageEvent", {"Event"})
    ANCESTORS("MouseEvent", {"Event", "UIEvent"})
    ANCESTORS("MutationEvent", {"Event"})
    ANCESTORS("PageTransitionEvent", {"Event"})
    ANCESTORS("PointerEvent", {"Event", "MouseEvent", "UIEvent"})
    ANCESTORS("PopStateEvent", {"Event"})
    ANCESTORS("ProcessingInstruction", {"CharacterData", "EventTarget", "Element"})
    ANCESTORS("ProgressEvent", {"Event"})
    ANCESTORS("PromiseRejectionEvent", {"Event"})
    ANCESTORS("ResourceProgressEvent", {"Event", "ProgressEvent"})
    ANCESTORS("SVGAElement", {"EventTarget", "Element", "SVGURIReference", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGAltGlyphDefElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGAltGlyphElement", {"EventTarget", "Element", "SVGURIReference", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGAltGlyphItemElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGAnimateColorElement", {"SVGElement", "EventTarget", "Element", "SVGAnimationElement"})
    ANCESTORS("SVGAnimateElement", {"SVGElement", "EventTarget", "Element", "SVGAnimationElement"})
    ANCESTORS("SVGAnimateMotionElement", {"SVGElement", "EventTarget", "Element", "SVGAnimationElement"})
    ANCESTORS("SVGAnimateTransformElement", {"SVGElement", "EventTarget", "Element", "SVGAnimationElement"})
    ANCESTORS("SVGAnimationElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGCircleElement", {"EventTarget", "Element", "SVGGeometryElement", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGClipPathElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGColorProfileElement", {"SVGElement", "EventTarget", "SVGURIReference", "Element"})
    ANCESTORS("SVGComponentTransferFunctionElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGCursorElement", {"SVGElement", "EventTarget", "SVGURIReference", "Element"})
    ANCESTORS("SVGDefsElement", {"SVGElement", "EventTarget", "SVGGraphicsElement", "Element"})
    ANCESTORS("SVGDescElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGDiscardElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGElement", {"EventTarget", "Element"})
    ANCESTORS("SVGEllipseElement", {"EventTarget", "Element", "SVGGeometryElement", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGFEBlendElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEColorMatrixElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEComponentTransferElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFECompositeElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEConvolveMatrixElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEDiffuseLightingElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEDisplacementMapElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEDistantLightElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEDropShadowElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEFloodElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEFuncAElement", {"SVGFilterPrimitiveStandardAttributes", "EventTarget", "SVGComponentTransferFunctionElement", "SVGElement", "Element"})
    ANCESTORS("SVGFEFuncBElement", {"SVGFilterPrimitiveStandardAttributes", "EventTarget", "SVGComponentTransferFunctionElement", "SVGElement", "Element"})
    ANCESTORS("SVGFEFuncGElement", {"SVGFilterPrimitiveStandardAttributes", "EventTarget", "SVGComponentTransferFunctionElement", "SVGElement", "Element"})
    ANCESTORS("SVGFEFuncRElement", {"SVGFilterPrimitiveStandardAttributes", "EventTarget", "SVGComponentTransferFunctionElement", "SVGElement", "Element"})
    ANCESTORS("SVGFEGaussianBlurElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEImageElement", {"SVGFilterPrimitiveStandardAttributes", "EventTarget", "SVGURIReference", "SVGElement", "Element"})
    ANCESTORS("SVGFEMergeElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEMergeNodeElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEMorphologyElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEOffsetElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFEPointLightElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFESpecularLightingElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFESpotLightElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFETileElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFETurbulenceElement", {"SVGFilterPrimitiveStandardAttributes", "SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFilterElement", {"SVGElement", "EventTarget", "SVGURIReference", "Element"})
    ANCESTORS("SVGFontElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFontFaceElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFontFaceFormatElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFontFaceNameElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFontFaceSrcElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGFontFaceUriElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGForeignObjectElement", {"SVGElement", "EventTarget", "SVGGraphicsElement", "Element"})
    ANCESTORS("SVGGElement", {"SVGElement", "EventTarget", "SVGGraphicsElement", "Element"})
    ANCESTORS("SVGGeometryElement", {"SVGElement", "EventTarget", "SVGGraphicsElement", "Element"})
    ANCESTORS("SVGGlyphElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGGlyphRefElement", {"SVGElement", "EventTarget", "SVGURIReference", "Element"})
    ANCESTORS("SVGGradientElement", {"SVGElement", "EventTarget", "SVGURIReference", "Element"})
    ANCESTORS("SVGGraphicsElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGHKernElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGHatchElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGHatchpathElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGImageElement", {"EventTarget", "Element", "SVGURIReference", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGLineElement", {"EventTarget", "Element", "SVGGeometryElement", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGLinearGradientElement", {"EventTarget", "SVGGradientElement", "SVGURIReference", "SVGElement", "Element"})
    ANCESTORS("SVGMPathElement", {"SVGElement", "EventTarget", "SVGURIReference", "Element"})
    ANCESTORS("SVGMarkerElement", {"SVGElement", "SVGFitToViewBox", "EventTarget", "Element"})
    ANCESTORS("SVGMaskElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGMetadataElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGMissingGlyphElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGPathElement", {"EventTarget", "Element", "SVGGeometryElement", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGPathSegArcAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegArcRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegClosePath", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoCubicAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoCubicRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoCubicSmoothAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoCubicSmoothRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoQuadraticAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoQuadraticRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoQuadraticSmoothAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegCurvetoQuadraticSmoothRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegLinetoAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegLinetoHorizontalAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegLinetoHorizontalRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegLinetoRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegLinetoVerticalAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegLinetoVerticalRel", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegMovetoAbs", {"SVGPathSeg"})
    ANCESTORS("SVGPathSegMovetoRel", {"SVGPathSeg"})
    ANCESTORS("SVGPatternElement", {"EventTarget", "SVGFitToViewBox", "SVGURIReference", "SVGElement", "Element"})
    ANCESTORS("SVGPolygonElement", {"EventTarget", "Element", "SVGGeometryElement", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGPolylineElement", {"EventTarget", "Element", "SVGGeometryElement", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGRadialGradientElement", {"EventTarget", "SVGGradientElement", "SVGURIReference", "SVGElement", "Element"})
    ANCESTORS("SVGRectElement", {"EventTarget", "Element", "SVGGeometryElement", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGSVGElement", {"EventTarget", "SVGZoomAndPan", "SVGFitToViewBox", "Element", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGScriptElement", {"SVGElement", "EventTarget", "SVGURIReference", "Element"})
    ANCESTORS("SVGSetElement", {"SVGElement", "EventTarget", "Element", "SVGAnimationElement"})
    ANCESTORS("SVGSolidcolorElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGStopElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGStyleElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGSwitchElement", {"SVGElement", "EventTarget", "SVGGraphicsElement", "Element"})
    ANCESTORS("SVGSymbolElement", {"EventTarget", "SVGFitToViewBox", "Element", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGTRefElement", {"EventTarget", "SVGTextContentElement", "Element", "SVGURIReference", "SVGElement", "SVGTextPositioningElement", "SVGGraphicsElement"})
    ANCESTORS("SVGTSpanElement", {"EventTarget", "SVGTextContentElement", "Element", "SVGElement", "SVGTextPositioningElement", "SVGGraphicsElement"})
    ANCESTORS("SVGTextContentElement", {"SVGElement", "EventTarget", "SVGGraphicsElement", "Element"})
    ANCESTORS("SVGTextElement", {"EventTarget", "SVGTextContentElement", "Element", "SVGElement", "SVGTextPositioningElement", "SVGGraphicsElement"})
    ANCESTORS("SVGTextPathElement", {"EventTarget", "SVGTextContentElement", "Element", "SVGURIReference", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGTextPositioningElement", {"EventTarget", "SVGTextContentElement", "Element", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGTitleElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGUseElement", {"EventTarget", "Element", "SVGURIReference", "SVGElement", "SVGGraphicsElement"})
    ANCESTORS("SVGVKernElement", {"SVGElement", "EventTarget", "Element"})
    ANCESTORS("SVGViewElement", {"EventTarget", "SVGZoomAndPan", "SVGFitToViewBox", "SVGElement", "Element"})
    ANCESTORS("SVGViewSpec", {"SVGZoomAndPan", "SVGFitToViewBox"})
    ANCESTORS("SecurityPolicyViolationEvent", {"Event"})
    ANCESTORS("ShadowRoot", {"DocumentFragment", "EventTarget", "Element", "DocumentOrShadowRoot"})
    ANCESTORS("Text", {"CharacterData", "EventTarget", "Element"})
    ANCESTORS("TextEvent", {"Event", "UIEvent"})
    ANCESTORS("TransitionEvent", {"Event"})
    ANCESTORS("UIEvent", {"Event"})
    ANCESTORS("VTTCue", {"TextTrackCue"})
    ANCESTORS("WheelEvent", {"Event", "MouseEvent", "UIEvent"})
    ANCESTORS("Window", {"EventTarget"})
}